name: C++ CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            compiler: gcc
          - os: ubuntu-latest
            compiler: llvm
          - os: windows-latest
            compiler: msvc
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: install tools ubuntu
        run: sudo apt-get -y update && sudo apt-get -y install llvm-dev libclang-dev clang g++ cmake
        if: ${{ contains(matrix.os, 'ubuntu' )}}
      - name: install tools windows
        uses: aminya/setup-cpp@v1
        if: ${{ contains(matrix.os, 'windows' )}}
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows' )}}
          cmake: true
      - name: install llvm and clang
        uses: KyleMayes/install-llvm-action@v1
        if: ${{ contains(matrix.os, 'windows' )}}
        with:
          version: "15"
      - name: Set LIBCLANG_PATH
        run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
        if: ${{ contains(matrix.os, 'windows' )}}
      - name: cmake
        run: cmake -S . -B ./build
      - name: build
        run: cmake --build ./build
