name: C++ CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            compiler: gcc
          - os: ubuntu-latest
            compiler: llvm
          - os: windows-latest
            compiler: msvc
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: install llvm-dev
        run: sudo apt-get -y update && sudo apt-get -y install llvm-dev libclang-dev clang
        if: ${{ contains(matrix.os, 'ubuntu' )}}
      - name: setup
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows' )}}
          cmake: true
      - name: cmake
        run: cmake -S . -B ./build
      - name: build
        run: cmake --build ./build
