name: C++ CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            compiler: gcc
          - os: ubuntu-latest
            compiler: llvm
#          - os: windows-latest
#            compiler: msvc
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: setup
        if: ${{ contains(matrix.compiler, 'llvm' )}}
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows' )}}
          cmake: true
      - name: setup
        if: ${{ !contains(matrix.compiler, 'llvm' )}}
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows' )}}
          llvm: 15
          cmake: true
      - name: cmake
        run: cmake -S . -B ./build
      - name: build
        run: cmake --build ./build
      - name: test
        run: cmake --build ./build -t test
